[package]
name = "variant_name_derive"
version = "0.0.1"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Derive VariantName trait"
license = "GPL-3.0-only"

[dependencies]
syn = "0.12"
quote = "0.4"

[lib]
proc-macro = true
