[package]
name = "aflak_primitives"
version = "0.0.3"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Define primitive functions for use with aflak"
license = "GPL-3.0-only"

[dependencies]
aflak_cake = { path = "../aflak_cake", version = "0.0.3" }
fitrs = "0.4.1"
lazy_static = "1.0"
ndarray = { version = "0.12", features = ["serde-1"] }
serde = "1.0"
serde_derive = "1.0"
variant_name = { path = "../variant_name", version = "0.0.1" }
variant_name_derive = { path = "../variant_name_derive", version = "0.0.1" }
